[package]
name = "huffman"
version = "0.1.1"
authors = ["Lúcás Meier <cronokirby@gmail.com>"]
edition = "2018"

[[bin]]
name = "huffman"

[dependencies]
structopt = "0.2.14"

[dev-dependencies]
criterion = "0.2"

[[bench]]
name = "benchmarks"
harness = false